mysite/urls.py
from django.contrib import admin
from django.urls import re_path, include

urlpatterns = [
    re_path(r'^admin/', admin.site.urls),
    re_path(r'^welcome/', include('welcome.urls')),
]

welcome/urls.py
from django.urls import re_path
from . import views
urlpatterns = [
    re_path(r'^$', views.index, name="index"),
    #127.0.0.1/welcome/
    re_path(r'^(?P<question_id>[0-9]+)/$',views.detail,name="welcome.detail"),
    #127.0.0.1/welcome/2
    re_path(r'^(?P<question_id>[0-9]+)/results$',views.results,name="results"),
    #127.0.0.1/welcome/2/results
    re_path(r'^(?P<question_id>[0-9]+)/vote$',views.vote,name="welcome.vote"),
    #127.0.0.1/welcome/2/vote
]

welcome/models.py
from django.db import models

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=100)
    pub_date = models.DateTimeField('data published')

    def __str__(self):
        return self.question_text
class choice(models.Model):
    choice_text=models.CharField(max_length=200)
    votes=models.IntegerField(default=0)
    question=models.ForeignKey(Question,on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_text

welcome/views.py
from django.shortcuts import render,get_object_or_404
from django.http import HttpResponse
from .models import Question
from django.template import loader, RequestContext
# Create your views here.
def index(request):
    latest_questions=Question.objects.order_by('-pub_date')[:5]
    template = loader.get_template('welcome/index.html')
    context = RequestContext(request, {
        'latest_questions':latest_questions
    })
    return HttpResponse(template.render(context.flatten()))


def detail(request, question_id):
    question = get_object_or_404(Question , pk=question_id)
    template = loader.get_template('welcome/detail.html')
    context = RequestContext(request, {
        'question':question
    })
    return HttpResponse(template.render(context.flatten()))

def results(request, question_id):
    return HttpResponse("These are the results of the question: %s" % question_id)

def vote(request,question_id):
    return HttpResponse("Vote on question: %s" % question_id)

welcome/templates/welcome/base.html
html head link
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" type="text/css" href="{% static 'welcome/style.css' %}" />
</head>
<body>
<hr>
<p>  </p>
<hr>
{% block main_content %}
{% endblock %}
{% include "welcome/footer.html" %}
</body>
</html>

welcome/templates/welcome/detail.html
{% extends 'welcome/base.html' %}
{% block main_content %}
<h1> {{question.question_text}}</h1>


<form action = {% url 'welcome.vote' question.id %}"  method="post">
    {% csrf_token %}
    {% for choice in question.choice_set.all %}
       <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{choice.id}}"/>
       <label for="choice{{forloop.counter}}"> {{choice.choice_text}}</label> <br>
    {% endfor %}

</form>


{% endblock %}

welcome/templates/welcome/footer.html
<hr>
<p>   </p>
<hr>

welcome/templates/welcome/index.html
{% extends 'welcome/base.html' %}
{% block main_content %}
<p> HELLO WORLD !! </p>
<p> Let's answer few questons to know about you .</p>
{% if latest_questions %}
     <ul>
         {% for question in latest_questions %}
            <li><a href="/welcome/{{question.id}}"><b> {{question.question_text}}</b></a></li>
         {% endfor %}
     </ul>
{% else %}
      <p> You don't have any question .Please add some </p>
{% endif %}

{% endblock %}